[2024-05-22 13:54:49,001] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.101.5:5000
[2024-05-22 13:54:49,002] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-05-22 13:54:52,089] 97 werkzeug - INFO - 127.0.0.1 - - [22/May/2024 13:54:52] "GET /predictdata HTTP/1.1" 200 -
[2024-05-22 13:55:10,290] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "/home/jagannath/ML_Project/src/utils.py", line 63, in load_object
    with open(file_path, "rb") as file_obj:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/model.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jagannath/ML_Project/src/pipeline/predict_pipeline.py", line 17, in predict
    model=load_object(file_path=model_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jagannath/ML_Project/src/utils.py", line 67, in load_object
    raise CustomException(e, sys)
src.exception.CustomException: Error occured in python script name [/home/jagannath/ML_Project/src/utils.py] line number [63] error message[[Errno 2] No such file or directory: 'artifacts/model.pkl']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jagannath/ML_Project/hell/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jagannath/ML_Project/hell/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jagannath/ML_Project/hell/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jagannath/ML_Project/hell/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jagannath/ML_Project/app.py", line 40, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jagannath/ML_Project/src/pipeline/predict_pipeline.py", line 25, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [/home/jagannath/ML_Project/src/pipeline/predict_pipeline.py] line number [17] error message[Error occured in python script name [/home/jagannath/ML_Project/src/utils.py] line number [63] error message[[Errno 2] No such file or directory: 'artifacts/model.pkl']]
[2024-05-22 13:55:10,297] 97 werkzeug - INFO - 127.0.0.1 - - [22/May/2024 13:55:10] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
